verzameldwerk_akismet.akismet_configuration:
    type: rest
    name_prefix: verzameldwerk_akismet.
    resource: verzameldwerk_akismet.akismet_configuration_controller

verzameldwerk_akismet.akismet_form_field:
    type: rest
    name_prefix: verzameldwerk_akismet.
    resource: verzameldwerk_akismet.akismet_form_field_controller

verzameldwerk_akismet.akismet_request:
    type: rest
    name_prefix: verzameldwerk_akismet.
    resource: verzameldwerk_akismet.akismet_request_controller

verzameldwerk_akismet.post_akismet-request_trigger:
    path: /akismet-requests/{id}.{_format}
    methods: POST
    defaults:
        _controller: verzameldwerk_akismet.akismet_request_controller::postTriggerAction
        _format: json
