name: Test application

on:
    pull_request:
    push:
        branches:
            - 'main'
            - '[0-9]+.x'
            - '[0-9]+.[0-9]+'

jobs:
    test:
        name: 'PHP ${{ matrix.php-version }} (${{ matrix.dependency-versions }})'
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                include:
                    - php-version: '7.4'
                      dependency-versions: 'lowest'
                      env:
                          SYMFONY_DEPRECATIONS_HELPER: disabled

                    - php-version: '8.0'
                      dependency-versions: 'highest'
                      env:
                          SYMFONY_DEPRECATIONS_HELPER: weak

                    - php-version: '8.1'
                      dependency-versions: 'highest'
                      env:
                          SYMFONY_DEPRECATIONS_HELPER: weak

        services:
            mysql:
                image: mysql:8.0
                env:
                    MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
                ports:
                    - 3306:3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5

        steps:
            - name: Checkout project
              uses: actions/checkout@v2

            - name: Install and configure PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  extensions: ctype, iconv, mysql

            - name: Install composer dependencies
              uses: ramsey/composer-install@v1
              with:
                  dependency-versions: ${{ matrix.dependency-versions }}

            - name: Bootstrap test environment
              run: composer bootstrap-test-environment

            - name: Execute test cases
              run: composer test

    lint:
        name: 'PHP Lint'
        runs-on: ubuntu-latest

        steps:
            - name: Checkout project
              uses: actions/checkout@v2

            - name: Install and configure PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.1
                  extensions: ctype, iconv, mysql

            - name: Install composer dependencies
              uses: ramsey/composer-install@v1
              with:
                  dependency-versions: highest

            - name: Lint Code
              run: composer lint
